Add nodelet to driver
enwaytech/livox_ros_driver2 pull request #6
Opened 2023-08-17 08:27 UTC by georgflick

2023-08-21 11:33 UTC, Roboterbastler commented on CMakeLists.txt
I haven't tested it but I think usually the nodelet file also needs to be installed by:

```cmake
install(FILES nodelets.xml DESTINATION ${CATKIN_PACKAGE_SHARE_DESTINATION})
```

2023-08-21 11:51 UTC, georgflick commented on CMakeLists.txt
true, I added that now in the commit:
https://github.com/enwaytech/livox_ros_driver2/pull/6/commits/a69afe4f9e450f5fdfc38d1a6d432c59e763cfc8

2023-08-21 13:34 UTC, Roboterbastler requested changes

2023-08-21 13:34 UTC, Roboterbastler commented on include/livox_ros_driver2/nodelet.h
> +  std::shared_ptr<livox_ros::DriverNode> livox_node_;
Maybe also include `<memory>` for completeness...

2023-08-21 13:34 UTC, Roboterbastler commented on nodelets.xml
> +  </library>
Indentation is displaced a bit

2023-08-21 13:34 UTC, Roboterbastler commented on src/driver_node.h
> +
Additional newline needed?

2023-08-21 13:34 UTC, Roboterbastler commented on package_ROS1.xml
> +  <exec_depend>pluginlib</exec_depend>
Could these be just `<depend>` tags?

2023-08-21 13:34 UTC, Roboterbastler commented on package.xml
> +  <exec_depend>pluginlib</exec_depend>
Could these be just `<depend>` tags?

2023-08-22 09:39 UTC, Roboterbastler approved these changes

2023-08-22 09:43 UTC, merged